# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: prcodesuggestion-develop
on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20]

    steps:
    - uses: actions/checkout@v4    
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x    
        
    - name: Install pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 9
        
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        
    - name: Install dependencies
      run: pnpm install -C ./src/WebApp
          
    - name: Restore dependencies
      run: dotnet restore ./src/PRCodeSuggestion.sln
      
    - name: Publish
      run: dotnet publish --no-restore ./src/PRCodeSuggestion.sln

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v3.2.1-node20
      with:
        name: nova
        path: ./src/WebApi/bin/Release/net8.0/publish/
          
